### ISSUE TITLE
Easier way/process to add news items

### ISSUE THREAD

**Issue by olliepuls** [cyber-institute/website#10]
Current ways of adding news articles/events/calendar items require too much developer overhead. Need to streamline the process to minimise the time we spend on this.

**Comment by jsindos** [comment]
Extracting the JSON into its own file separate from React is probably the simplest solution to start. Not 100% if this is user friendly enough for Jenalle but probably a good starting point to see what she thinks.

The current structure of the news items is as follows:

```
const news = {
  title: 'News',
  sections: [{
    id: '2',
    component: 'NewsArticle',
    props: {
      head: 'VC’s interview with Chief Information Security Officer',
      byline: "Vice-Chancellor Brian Schmidt spoke to the Chief Information Security Officer, Suthagar Seevaratnum, who explains implications for the cybersecurity during the pandemic. Please check out the video.",
      author: 'ANU',
      date: '',
      imageSource: RSA2,
      sizeName: 'col-md-3 col-xs-12',
      link: 'https://www.youtube.com/watch?v=OYzuoi_a1i0&feature=youtu.be'
    }
  },
```

It's probably going to be difficult for her to figure out how to put images in so this is something else that needs to be looked at.

**Comment by olliepuls** [comment]
Have changed the way articles are added/stored.
There is now an 'items' directory containing separate files for articles, blogs, events, news & podcasts. Each of these files contains an array of NewsArticle objects. If a new article needs to be added all that would be required is to add another json object to the top of the array. The 9 most recent articles are included in the website. 

Janelle could either add or submit objects in this format along with an appropriately sized image and these could be copied in fairly easily by whoever.

![image](https://user-images.githubusercontent.com/53168353/85253187-f7009900-b4a0-11ea-84b3-8afd7732e494.png)
