### ISSUE TITLE
Courses page 

### ISSUE THREAD

**Issue by b00mhs99** [cyber-institute/website#11]
[CI Website Course Pgs Changes 220620.docx](https://github.com/cyber-institute/website/files/4811029/CI.Website.Course.Pgs.Changes.220620.docx)

**Comment by olliepuls** [comment]
Begun adding page in coursesUpdate branch on website. Feel free to leave comments for improvements etc.

**Comment by olliepuls** [comment]
https://courses-page.herokuapp.com/courses

**Comment by olliepuls** [comment]
Waiting on enrolment links from finance
