### ISSUE TITLE
Individual page for each media item (news, events etc) so they can be linked to from social media

### ISSUE THREAD

**Issue by jsindos** [cyber-institute/website#13]
We want an individual page for each of these items so they can be linked to from social media.

<img width="1448" alt="MacBook Pro - 2 (2)" src="https://user-images.githubusercontent.com/8110172/85963077-632a5200-b9f7-11ea-8e25-b52583203fd7.png">

With layout grid:

<img width="737" alt="Screen Shot 2020-06-29 at 10 55 17 am" src="https://user-images.githubusercontent.com/8110172/85963049-4261fc80-b9f7-11ea-91c0-f1f86dfb9694.png">

**Comment by olliepuls** [comment]
in branch new-article-page. Can't seem to get pages to render directly from URL
